name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - name: Publish HTML Report
      run: |
        # Assuming your Playwright HTML report is generated in a folder named 'report'
        mkdir -p ${{ github.workspace }}/docs  # Create a 'docs' folder if it doesn't exist
        cp -r playwright-report/* ${{ github.workspace }}/docs  # Copy the report to 'docs' folder
      # Commit and push the changes to a GitHub Pages branch (e.g., gh-pages)
      # Replace <username> with your GitHub username and <repository> with your repo name
      - name: Commit and Push HTML Report to GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b gh-pages
          git add docs/
          git commit -m "Publish Playwright HTML report"
          git push origin gh-pages

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
