name: Playwright Tests and Deploy Report
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload Test Report Artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Download Test Report Artifact
        uses: actions/download-artifact@v2
        with:
          name: playwright-report

      - name: Create docs directory
        run: mkdir -p docs

      - name: Copy Test Report to docs directory
        run: cp -r ${{ github.workspace }}/playwright-report/. docs/

      - name: Deploy Test Report to GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout $GITHUB_REF
          git add docs/
          git commit -m "Update Playwright test report [skip ci]"
          git push origin $GITHUB_REF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
